services:
  - type: web
    name: resto-frontend      # Matches your GitHub repo name
    env: static
    staticPublishPath: build  # React build output
    plan: free
    buildCommand: npm install && npm run build
    envVars:
      - key: REACT_APP_API_URL
        value: https://resto-backend-0wwz.onrender.com/api   # Replace with your actual backend Render URL
    routes:
      - type: static
        path: /
